# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 430b353f971ccec0999d6a55a6427e47efbdb85674cfb8d29be3c53022891f0c7c0b3346d9bf846d161db7eeb9cb6ec9435f6ad9d1e6f2406c99e4239291bb92

test:
  secret_key_base: 73f39d6bae17edde1b47e7f689292671f9e333970fc3c4fd1b5ad390e579b06ddf99e9aa53f1c3496caa309aec1492c89c4c3cfe5b1a10e10164210320a89915

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
